config/routes.rb
Rails.application.routes.draw do
  resources :spreadsheets
  resources :scrapes, :except => [:edit, :update] do
    resources :spreadsheets, :only => [:update]
  end
  resources :settings, :except => [:new, :show, :edit]
  get 'setup', :to => 'setup#index'
  root 'setup#index'
end

app/views/shared/_errors.html.erb
<% if object.errors.present? %>
  <div class="alert alert-danger">
    <%
    field ||= nil
    error_messages_for(object, field) do |error|
    %>
      <%= error %>
      <br/>
    <% end %>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:success] %>
  <div class="alert alert-success">
    <%= flash[:success] %>
  </div>
<% end %>

<% if flash[:notice] %>
  <div class="alert alert-info">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:warning] %>
  <div class="alert alert-warning">
    <%= flash[:warning] %>
  </div>
<% end %>

<% if flash[:error] %>
  <div class="alert alert-danger">
    <%= flash[:error] %>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav-collapse-container" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to('QuoraBot3000', root_path, :class => 'navbar-brand') %>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="main-nav-collapse-container">
      <ul class="nav navbar-nav navbar-right">
        <li>

          <%= link_to('Spreadsheets', spreadsheets_path) %>
          
        </li>
        <li>

          <%= link_to('Scrapes', scrapes_path) %>
          
        </li>
        <li>

          <%= link_to('Setup', setup_path) %>
          
        </li>
        <li>

          <%= link_to('Settings', settings_path) %>
          
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>