config/routes.rb
Rails.application.routes.draw do
  resources :spreadsheets
  resources :scrapes, :except => [:edit, :update] do
    resources :spreadsheets, :only => [:update]
  end
  resources :settings, :except => [:new, :show, :edit]
  get 'setup', :to => 'setup#index'
  root 'setup#index'
end

app/models/setting.rb
class Setting < ActiveRecord::Base
  validates :key,
            :presence => true,
            :uniqueness => true

  validates :value,
            :presence => true

  before_destroy :deny_if_required

  def self.key(key)
    Setting.find_by_key(key) || Setting.new(:key => key)
  end

  def self.client_credentials?
    Setting.key(:client_id).persisted? &&
    Setting.key(:client_secret).persisted?
  end

  def self.redirect_token?
    Setting.key(:redirect_token).persisted?
  end

  def self.access_token?
    Setting.key(:access_token).persisted?
  end


  private
  def deny_if_required
    if [:client_id, :client_secret, :access_token].include?(key.to_sym) && Spreadsheet.count > 0
      errors.add(:base, "Cannot delete required credentials with existing spreadsheets")
    end
    errors.empty?
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, :only => [:update, :destroy]

  def index
    @app_name = Setting.key(:app_name)
    @app_version = Setting.key(:app_version)
    @client_id = Setting.key(:client_id)
    @client_secret = Setting.key(:client_secret)
    @redirect_token = Setting.key(:redirect_token)
    @access_token = Setting.key(:access_token)
  end

  def create
    @setting = Setting.new(setting_params)
    if @setting.save
      flash[:success] = 'Setting created'
    else
      flash[:error] = 'Setting not created'
    end
    redirect_to request.referer ? request.referer : settings_path
  end

  def update
    if @setting.update(setting_params)
      flash[:success] = 'Setting updated'
    else
      flash[:error] = 'Setting not updated'
    end
    redirect_to settings_path
  end

  def destroy
    if @setting.destroy
      flash[:success] = 'Setting destroyed'
    else
      flash[:error] = 'Setting not destroyed: ' +
        @setting.errors.full_messages.join(', ')
    end
    redirect_to settings_path
  end


  private
  def set_setting
    @setting = Setting.find_by_id(params[:id])
  end

  def setting_params
    params.require(:setting)
      .permit(
        :key,
        :value
      )
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%
setting_title = setting.key.to_s.titleize
setting_title += setting_title == 'Client' ? ' ID' : ''
%>

<%= form_for(setting) do |f| %>

  <div class="form-group">
    <h3>

      <%= setting_title %>

    </h3>
  </div>

  <% if setting.new_record? %>
    <div class="form-group">
        <%= f.text_field(:value, :class => 'form-control') %>
    </div>

    <%= f.hidden_field(:key, :class => 'form-control') %>
    <%= f.submit("Set #{setting_title}", :class => 'btn btn-primary') %>

  <% else %>

    <%= setting_title %> is set - 
    <%= link_to("Delete #{setting_title}", setting_path(setting), :method => :delete, :class => 'btn btn-danger', :data => {:confirm => "Are you sure you want to delete the #{setting_title}?"}) %>

  <% end %>
<% end %>

<br>

app/views/settings/index.html.erb
<div class="row">
  <div class="col-xs-12">
    
    <header class="page-header clearfix">
      <h1 class="pull-left">
        Settings Index
      </h1>
    </header>

    <div class="alert alert-warning">
      Once set you should not change your Client ID and Client Secret
      unless you need to switch API accounts.
    </div>
    <%= render :partial => 'form', :locals => {:setting => @client_id} %>
    <%= render :partial => 'form', :locals => {:setting => @client_secret} %>
    <br><br>

    <div class="alert alert-warning">
      No need to change or try to set the Redirect Token here.
      It is merely available here for convenience.
      Once the access token is set, it is most likely useless.
    </div>
    <%= render :partial => 'form', :locals => {:setting => @redirect_token} %>
    <br><br>

    <div class="alert alert-danger">
      Don't delete or try to set the Access Token manually!
      QuoraBot3000 sets the Access Token automatically when
      retreiving and saving the redirect token.
    </div>
    <%= render :partial => 'form', :locals => {:setting => @access_token} %>
    <br><br>

    <div class="alert alert-info">
      Supplying an App Name and App Version are optional.
    </div>
    <%= render :partial => 'form', :locals => {:setting => @app_name} %>
    <%= render :partial => 'form', :locals => {:setting => @app_version} %>
    <br><br>

  </div><!-- col -->
</div><!-- row -->