config/routes.rb
Rails.application.routes.draw do
  resources :spreadsheets
  resources :scrapes, :except => [:edit, :update] do
    resources :spreadsheets, :only => [:update]
  end
  resources :settings, :except => [:new, :show, :edit]
  get 'setup', :to => 'setup#index'
  root 'setup#index'
end

app/models/scrape.rb
class Scrape < ActiveRecord::Base
  belongs_to :spreadsheet
  serialize :data, JSON

  validate  :spreadsheet_exists,
            :spreadsheet_has_data_worksheet,
            :spreadsheet_has_map_worksheet


  private
  def spreadsheet_exists
    unless Spreadsheet.find_by_id(self.spreadsheet_id)
      errors.add(:spreadsheet, 'must exist')
    end
  end

  def spreadsheet_has_data_worksheet
    spreadsheet = Spreadsheet.find_by_id(self.spreadsheet_id)
    unless spreadsheet && spreadsheet.data_gid
      errors.add(:spreadsheet, 'must have a data worksheet set')
    end
  end

  def spreadsheet_has_map_worksheet
    spreadsheet = Spreadsheet.find_by_id(self.spreadsheet_id)
    unless spreadsheet && spreadsheet.map_gid
      errors.add(:spreadsheet, 'must have a map worksheet set')
    end
  end
end

app/controllers/scrapes_controller.rb
class ScrapesController < ApplicationController
  before_action :require_credentials
  before_action :set_scrape, :only => [:show, :destroy]

  def index
    @scrapes = Scrape.order(:created_at => 'DESC')
  end

  def show
  end

  def new
    @scrape = Scrape.new
  end

  def create
    @scrape = Scrape.new(scrape_params)
    if @scrape.save
      flash[:success] = 'Scrape created'
      redirect_to @scrape
    else
      flash.now[:error] = 'Scrape not created'
      render :new
    end
  end

  def destroy
    if @scrape.destroy
      flash[:success] = 'Scrape destroyed'
    else
      flash[:error] = 'Scrape not destroyed'
    end
    redirect_to scrapes_path
  end


  private
  def set_scrape
    @scrape = Scrape.find_by_id(params[:id])
  end

  def scrape_params
    params.require(:scrape)
      .permit(
        :spreadsheet_id
      )
  end
end

app/helpers/scrapes_helper.rb
module ScrapesHelper
end

app/views/scrapes/_form.html.erb
<%= render :partial => 'shared/errors', :locals => {:object => scrape} %>

<%= form_for(scrape) do |f| %>
  <div class="form-group">
    <%= f.label(:spreadsheet_id, 'Choose a spreadsheet to scrape with...') %>
    <%= f.collection_select(
      :spreadsheet_id,
      Spreadsheet.all,
      :id,
      Proc.new{|spreadsheet| "#{spreadsheet.title} - #{spreadsheet.key}"},
      {:include_blank => true},
      {:class => 'form-control'}
    ) %>
  </div>
  <%= f.submit('Create Scrape', :class => 'btn btn-primary') %>
<% end %>

app/views/scrapes/_scrape.html.erb
<div class="row">
  <div class="col-xs-12">

    <div class="scrape">
      <h2>
        Scrape for:
        <%= link_to(scrape.spreadsheet.title, spreadsheet_path(scrape.spreadsheet)) %>
      </h2>

      <table class="table">
        <thead>
          <tr>
            <th>
              Key
            </th>
            <th>
              Value
            </th>
          </tr>
        </thead>
        <tbody>

          <tr>
            <td>
              ID
            </td>
            <td>
              <%= scrape.id %>
            </td>
          </tr>

          <tr>
            <td>
              Time Performed
            </td>
            <td>
              <%= scrape.updated_at.strftime('%m/%d/%Y - %H:%M:%S (UTC)') %>
            </td>
          </tr>

          <tr>
            <td>
              <%= link_to('Show Data', '#', :class => "scrape-data-toggle", :data => {:hidden => true, :scrape_id => scrape.id}) %>
            </td>
            <td>

              <% if scrape.data %>

                <pre id="scrape-data-<%= scrape.id %>" class="scrape-data"><%= JSON.pretty_generate(JSON.parse(scrape.data.to_json)) %></pre>

              <% else %>

                <p class="text-danger">
                  No data
                </p>

              <% end %>
            </td>
          </tr>

        </tbody>
      </table>
    </div><!-- scrape -->

    <div class="actions">
      <%= link_to('Upload Scrape Data to Spreadsheet', scrape_spreadsheet_path(scrape, scrape.spreadsheet), :method => :put, :class => 'btn btn-primary') %>

      <%= link_to('Delete Scrape', scrape_path(scrape), :method => :delete, :class => 'btn btn-danger', :data => {:confirm => 'Are you sure you want to delete this scrape?'}) %>
    </div><!-- actions -->

  </div><!-- col -->
</div><!-- row -->

app/views/scrapes/index.html.erb
<div class="row">
  <div class="col-xs-12">
    
    <header class="page-header clearfix">
      <h1 class="pull-left">
        Scrapes Index
        <small>
          (Ordered by Neweset - Oldest)
        </small>
      </h1>

      <%= link_to('+ New Scrape', new_scrape_path, :class => 'btn btn-primary btn-lg pull-right') %>
    </header>

    <% if @scrapes.present? %>
      
      <ul class="list-group">
        <% @scrapes.each do |scrape| %>
          <li class="list-group-item">
            
            <%= render scrape %>

          </li>
        <% end %>
      </ul>

    <% else %>

      <p class="text-warning">
        No scrapes yet
      </p>

    <% end %>

  </div><!-- col -->
</div><!-- row -->

app/views/scrapes/new.html.erb
<div class="row">
  <div class="col-xs-12">
    
    <header class="page-header">
      <h1>
        New Scrape
      </h1>
    </header>

    <div class="form-container">
      <%= render :partial => 'form', :locals => {:scrape => @scrape} %>
    </div>

  </div><!-- col -->
</div><!-- row -->

app/views/scrapes/show.html.erb
<%= render @scrape %>