config/routes.rb
Rails.application.routes.draw do
  resources :spreadsheets
  resources :scrapes, :except => [:edit, :update] do
    resources :spreadsheets, :only => [:update]
  end
  resources :settings, :except => [:new, :show, :edit]
  get 'setup', :to => 'setup#index'
  root 'setup#index'
end

app/models/spreadsheet.rb
class Spreadsheet < ActiveRecord::Base
  has_many :scrapes, :dependent => :destroy

  after_initialize :create_internal_spreadsheet
  after_initialize :populate_attributes

  validates :key,
            :presence => true,
            :uniqueness => true

  validate :create_internal_spreadsheet

  attr_accessor :internal_spreadsheet,
                :data_worksheet,
                :map_worksheet

  def refresh
    populate_attributes
  end

  # Forwards any missing methods
  # to the @internal_spreadsheet object
  # only if it responds to the method
  def method_missing(name, *args)
    if @internal_spreadsheet.respond_to?(name)
      args.length > 0 ? @internal_spreadsheet.send(name, args) : @internal_spreadsheet.send(name)
    else
      raise NoMethodError, "Undefined method #{name} for Spreadsheet"
    end
  end

  # Generate list of URLs
  def generate_urls
    @data_worksheet.sanitized_urls
  end

  # Upload
  def upload(scrape_id)
    scrape = self.scrapes.find_by_id(scrape_id)
    @data_worksheet.write(scrape.data)
  end


  private
  # Used as an after_initialize callback
  # and validation callback
  # 
  # Creates an internal spreadsheet from API
  # If creation is unsuccessful
  # it appends the API's exception message
  # as a validation error to the model
  # instance
  def create_internal_spreadsheet
    begin
      GoogleDriveAPI.init
      @internal_spreadsheet = GoogleDriveAPI.session
        .spreadsheet_by_key(key) if key && key.chars.present?
    rescue Google::APIClient::ClientError, GoogleDrive::Error, StandardError => e
      self.errors.add(:key, " raised a Google API error - #{e.message}")
    end
  end

  def populate_attributes
    if @internal_spreadsheet
      @map_worksheet = MapWorksheet.new(
        :worksheet => @internal_spreadsheet.worksheet_by_gid(map_gid),
        :spreadsheet => self
      ) if map_gid

      if data_gid
        @data_worksheet = DataWorksheet.new(
          :worksheet => @internal_spreadsheet.worksheet_by_gid(data_gid),
          :spreadsheet => self
        )
        @data_worksheet.create_named_ranges(@map_worksheet)
      end
    end
  end
end

app/controllers/spreadsheets_controller.rb
class SpreadsheetsController < ApplicationController
  before_action :require_credentials
  before_action :set_spreadsheet, :only => [:show, :edit, :update, :destroy]

  def index
    @spreadsheets = Spreadsheet.all
  end

  def show
  end

  def new
    @spreadsheet = Spreadsheet.new
  end

  def edit
  end

  def create
    @spreadsheet = Spreadsheet.new(spreadsheet_params)
    if @spreadsheet.save
      flash[:success] = 'Spreadsheet linked'
      redirect_to spreadsheets_path
    else
      flash.now[:error] = 'Spreadsheet not linked'
      render :new
    end
  end

  def update
    if params[:scrape_id]
      upload_scrape_data_to_spreadsheet
    else
      update_spreadsheet_reference
    end
  end

  def destroy
    if @spreadsheet.destroy
      flash[:success] = 'Spreadsheet reference destroyed'
    else
      flash[:error] = 'Spreadsheet reference not destroyed'
    end
    redirect_to spreadsheets_path
  end


private
  def set_spreadsheet
    @spreadsheet = Spreadsheet.find_by_id(params[:id])
  end

  def spreadsheet_params
    params.require(:spreadsheet)
      .permit(
        :key,
        :data_gid,
        :map_gid
      )
  end

  def upload_scrape_data_to_spreadsheet
    if @spreadsheet.upload(params[:scrape_id])
      flash[:success] = 'Scrape data uploaded'
    else
      flash[:error] = 'Scrape data not uploaded'
    end
    redirect_to scrapes_path
  end

  def update_spreadsheet_reference
    if @spreadsheet.update(spreadsheet_params)
      flash[:success] = 'Spreadsheet updated'
      redirect_to spreadsheet_path(@spreadsheet)
    else
      flash[:error] = 'Spreadsheet not updated'
      render :edit
    end
  end
end

app/helpers/spreadsheets_helper.rb
module SpreadsheetsHelper
end

app/views/spreadsheets/_form.html.erb
<%= render :partial => 'shared/errors', :locals => {:object => spreadsheet} %>

<%= form_for(spreadsheet) do |f| %>
  <% if spreadsheet.persisted? %>

    <p class="text-muted">
      Key: <%= spreadsheet.key %>
    </p>

    <div class="form-group">
      <%= f.label(:data_gid, 'Data Worksheet GID') %>
      <%= f.collection_select(
        :data_gid,
        spreadsheet.worksheets,
        :gid,
        Proc.new{|worksheet| "Title: #{worksheet.title} | GID: #{worksheet.gid}"},
        {},
        {:class => 'form-control'}
      ) %>
    </div>
    <div class="form-group">
      <%= f.label(:map_gid, 'Map Worksheet GID') %>
      <%= f.collection_select(
        :map_gid,
        spreadsheet.worksheets,
        :gid,
        Proc.new{|worksheet| "Title: #{worksheet.title} | GID: #{worksheet.gid}"},
        {},
        {:class => 'form-control'}
      ) %>
    </div>

  <% else %>

    <div class="form-group">
      <%= f.label(:key, 'Spreadsheet Key') %>
      <%= f.text_field(:key, :class => 'form-control') %>
    </div>

  <% end %>

  <%= f.submit(
    spreadsheet.persisted? ? 'Update Spreadsheet Reference' : 'Link Local Reference to Spreadsheet with this Key',
    :class => 'btn btn-primary'
    ) %>
<% end %>

app/views/spreadsheets/_spreadsheet.html.erb
<div class="row">
  <div class="col-xs-12">

    <div class="spreadsheet">
      <h2>
        Title: <%= spreadsheet.title %>
      </h2>
      <table class="table">
        <thead>
          <tr>
            <th>Key</th>
            <th>Value</th>
          </tr>
        </thead>
        <tbody>

          <tr>
            <td>
              Spreadsheet Link
            </td>
            <td>
              <%= link_to(spreadsheet.human_url, spreadsheet.human_url, :target => '_blank') %>
            </td>
          </tr>
          
          <tr>
            <td>
              Key
            </td>
            <th>
             <%= spreadsheet.key %> 
            </th>
          </tr>

          <tr>
            <td>
              Number of Worksheets
            </td>
            <td>
              <%= spreadsheet.worksheets.length %>
            </td>
          </tr>

          <tr>
            <td>
              Data Worksheet
            </td>
            <td>

              <% if spreadsheet.data_gid %>

                <%= link_to("Title: #{spreadsheet.data_worksheet.title} | GID: #{spreadsheet.data_worksheet.gid}", spreadsheet.data_worksheet.human_url, :target => '_blank') %>

              <% else %>

                <span class="text-danger">
                  Click 'Edit Spreadsheet Reference' to add data worksheet
                </span>

              <% end %>

            </td>
          </tr>

          <tr>
            <td>
              Map Worksheet
            </td>
            <td>

              <% if spreadsheet.data_gid %>

                <%= link_to("Title: #{spreadsheet.map_worksheet.title} | GID: #{spreadsheet.map_worksheet.gid}", spreadsheet.map_worksheet.human_url, :target => '_blank') %>

              <% else %>

                <span class="text-danger">
                  Click 'Edit Spreadsheet Reference' to add map worksheet
                </span>

              <% end %>

            </td>
          </tr>

        </tbody>
      </table>

      <div class="actions">
        <%= link_to('Edit Spreadsheet Reference', edit_spreadsheet_path(spreadsheet), :class => 'btn btn-primary') %>

        <%= link_to('Delete Local Reference to this Spreadsheet', spreadsheet_path(spreadsheet), :method => :delete, :class => 'btn btn-danger', :data => {:confirm => 'Are you sure you want to delete this spreadsheet reference? This will delete all scrapes created with this spreadsheet reference!'}) %>
      </div><!-- actions -->

    </div><!-- spreadsheet -->

  </div><!-- col -->
</div><!-- row -->

app/views/spreadsheets/edit.html.erb
<div class="row">
  <div class="col-xs-12">

    <header class="page-header">
      <h1>
        Edit Spreadsheet Reference
      </h1>
    </header>

    <div class="form-container">
      <%= render :partial => 'form', :locals => {:spreadsheet => @spreadsheet} %>
    </div>

  </div><!-- col -->
</div><!-- row -->

app/views/spreadsheets/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <header class="page-header clearfix">
      <h1 class="pull-left">
        Referenced Spreadsheets Index
      </h1>

      <%= link_to('+ Link New Local Spreadsheet Reference', new_spreadsheet_path, :class => 'btn btn-primary btn-lg pull-right') %>
    </header>

    <% if @spreadsheets.present? %>
      
      <ul class="list-group">
        <% @spreadsheets.each do |spreadsheet| %>
          <li class="list-group-item">
            
            <%= render spreadsheet %>

          </li>
        <% end %>
      </ul>

    <% else %>

      <p class="text-warning">
        No spreadsheets yet
      </p>

    <% end %>

  </div>
</div>

app/views/spreadsheets/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <header class="page-header">
      <h1>
        New Spreadsheet Reference
      </h1>
    </header>
    <div class="form-container">
      <%= render :partial => 'form', :locals => {:spreadsheet => @spreadsheet} %>
    </div>
  </div>
</div>

app/views/spreadsheets/show.html.erb
<%= render @spreadsheet %>